#spring.application.name=Java_Technical_Assignment
server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital
    username: root
    password: admin@sql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
